Ext.define('PaperVan.view.CustomerList', {
	extend : 'Ext.List',
	xtype : 'customerList',
	config : {
		title : 'Customers',
		grouped : true,
		indexBar : true,
		flex : 3,
		refreshHeightOnUpdate : true,
		variableHeights : true,
		itemHeight : 60,
		itemTpl : [
				'<tpl if="creditAvailable &lt;= CREDIT_LOW  || creditBlock == CREDIT_BLOCK">',
				'<b><div class="cust_list_name" id="red">{custName}</div></b><br></tpl>',
				'<tpl if="creditUsed &lt;= CREDIT_USED_HIGH && creditAvailable &gt; CREDIT_LOW && creditBlock == CREDIT_NOT_BLOCK">',
				'<b><div class="cust_list_name" id="green">{custName}</div></b><br></tpl>',
				'<tpl if="creditUsed &gt; CREDIT_USED_HIGH && creditAvailable &gt; CREDIT_LOW && creditBlock == CREDIT_NOT_BLOCK">',
				'<b><div class="cust_list_name" id="yellow">{custName}</div></b><br></tpl>',
				'<div class="cust_list_no"># {custNo}</div>',
				'<div class="cust_list_crlim_text">Cr. Lmt: </div>',
				'<div class="cust_list_crlim_val"><b>{[number(values.creditLimit)]}</b></div>',
				'<div class="cust_list_cravl_val"><b>{[number(values.creditAvailable)]}</b></div>',
				'<div class="cust_list_cravl_text">Cr. Avl: </div>',
				'<tpl if="visitPeriod.length &gt; 0">',
				'<table style="width:100%">',
				'<tr>',
				'<td style="width:60%"><div class="cust_address"><a href="maps:q={address}">{address}</a></div></td>',
				'<td style="width:40%"><div class="cust_visit">Routine: <b>{[getVisitPeriodText(values.visitPeriod)]}</b></div></td>',
				'</tr>',
				'<tr>',
				'<td style="width:100%"><div class="cust_schedule">Visit on: ',
				'<tpl if="monday == \'X\'">',
				'<input type="checkbox" onclick="return false" checked/><b>Mon</b> ',
				'</tpl>',								
				'<tpl if="monday == \'\'">',
				'<input type="checkbox" onclick="return false"/>Mon ',
				'</tpl>',								
				'<tpl if="tuesday == \'X\'">',
				'<input type="checkbox" onclick="return false" checked/><b>Tue</b> ',
				'</tpl>',								
				'<tpl if="tuesday == \'\'">',
				'<input type="checkbox" onclick="return false"/>Tue ',
				'</tpl>',								
				'<tpl if="wednesday == \'X\'">',
				'<input type="checkbox" onclick="return false" checked/><b>Wed</b> ',
				'</tpl>',								
				'<tpl if="wednesday == \'\'">',
				'<input type="checkbox" onclick="return false"/>Wed ',
				'</tpl>',								
				'<tpl if="thursday == \'X\'">',
				'<input type="checkbox" onclick="return false" checked/><b>Thu</b> ',
				'</tpl>',								
				'<tpl if="thursday == \'\'">',
				'<input type="checkbox" onclick="return false"/>Thu ',
				'</tpl>',								
				'<tpl if="friday == \'X\'">',
				'<input type="checkbox" onclick="return false" checked/><b>Fri</b> ',
				'</tpl>',								
				'<tpl if="friday == \'\'">',
				'<input type="checkbox" onclick="return false"/>Fri ',
				'</tpl>',								
				'<tpl if="saturday == \'X\'">',
				'<input type="checkbox" onclick="return false" checked/><b>Sat</b> ',
				'</tpl>',								
				'<tpl if="saturday == \'\'">',
				'<input type="checkbox" onclick="return false"/>Sat ',
				'</tpl>',								
				'<tpl if="sunday == \'X\'">',
				'<input type="checkbox" onclick="return false" checked/><b>Sun</b> ',
				'</tpl>',								
				'<tpl if="sunday== \'\'">',
				'<input type="checkbox" onclick="return false"/>Sun ',
				'</tpl>',
				'</td>',								
				'</tr>',
				'</table>',				
				'</tpl>',				
				],
		store : {
			type : 'customer'
		}
	}
});